# Generated by Django 4.0.4 on 2022-05-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('units', models.CharField(max_length=250)),
                ('devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_api.devices')),
            ],
        ),
    ]
